//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class formmer
    {
        public int id { get; set; }
        public string name_former { get; set; }
        public Nullable<int> from_year { get; set; }
        public Nullable<int> to_year { get; set; }
    }
}
