//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MunicipalEntities : DbContext
    {
        public MunicipalEntities()
            : base("name=MunicipalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<education> educations { get; set; }
        public virtual DbSet<formmer> formmers { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<professionell> professionells { get; set; }
        public virtual DbSet<speech> speeches { get; set; }
        public virtual DbSet<visiting> visitings { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
    }
}
