//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Municipal
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_dates { get; set; }
        public Nullable<int> number { get; set; }
        public string type_pub { get; set; }
        public string limit { get; set; }
    }
}
